spring.application.name=spms-backend

# Temporary demo database
spring.datasource.url=jdbc:h2:mem:spms_db;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
spring.datasource.username=root
spring.datasource.password=Vidhya_15@2008
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Render port
server.port=${PORT:8080}

# JWT
spms.jwt.secret=spms-demo-secret-2026-change-this-later-very-long-key
spms.jwt.expiration-ms=86400000

# CORS
spms.cors.allowed-origin=*

# Queue
spms.queue.average-service-minutes=5